version: '3'
services:
    mysql:
        image: mysql:5.6
        ports:
          - "3307:3306"
        environment:
          - MYSQL_DATABASE=chess
          - MYSQL_USER=docker
          - MYSQL_PASSWORD=123456
          - MYSQL_ROOT_PASSWORD=root
        restart: always
        volumes:
          - "./mysql/db:/var/lib/mysql"
          - "./mysql/init:/docker-entrypoint-initdb.d/"
          - "./mysql/conf/my.cnf:/etc/my.cnf"